### ISSUE TITLE
Why does this custom background link not display the image correctly?

### ISSUE THREAD

**Issue by gaurav-95** [jacebrowning/memegen#804]
I used the following link to generate a meme:

https://api.memegen.link/images/custom/_/When_you_realize_you_left_your_oven_on_at_home_but_you're_already_in_Hawaii_.png#VacationProblems.png?background=https://static01.nyt.com/images/2023/06/10/multimedia/10cnn-wpfv/10cnn-wpfv-facebookJumbo.jpg

bg_image = https://static01.nyt.com/images/2023/06/10/multimedia/10cnn-wpfv/10cnn-wpfv-facebookJumbo.jpg
caption text = When_you_realize_you_left_your_oven_on_at_home_but_you're_already_in_Hawaii

The background shows up as striped diagonals instead of the provided background image.

![image](https://github.com/jacebrowning/memegen/assets/59512848/3744b513-a68c-4db5-ace8-dce84ba1a111)

**Comment by jacebrowning** [comment]
The backend is interpreting your request as https://api.memegen.link/images/custom/_/When_you_realize_you_left_your_oven_on_at_home_but_you're_already_in_Hawaii_.png since `#` ([URI fragments](https://en.wikipedia.org/wiki/URI_fragment)) are not sent to web servers. 

You need to escape the `#` character in URLs: https://memegen.link/#special-characters

Like this: https://api.memegen.link/images/custom/_/When_you_realize_you_left_your_oven_on_at_home_but_you're_already_in_Hawaii_.png~hVacationProblems.png?background=https://static01.nyt.com/images/2023/06/10/multimedia/10cnn-wpfv/10cnn-wpfv-facebookJumbo.jpg

If you use the POST endpoint this escaping is done automatically: https://api.memegen.link/docs/#/Images/post~Images.create_custom
