### ISSUE TITLE
Text is slightly trimmed sometimes

### ISSUE THREAD

**Issue by LatinSuD** [jacebrowning/memegen#816]
In some situations the text is slightly cut at the bottom.

You can see it here. 

https://api.memegen.link/images/custom/_/enjoy_enjoy_enjoy_enjoy_enjoy_enjoy_enjoy.jpg?font=impact&background=https://latinsud.com/pub/meme/files/fernando-simon-covid.jpg

**Comment by jacebrowning** [comment]
Thanks for the bug report!

The issue seems to be a quirk with the Impact font so I adjusted the offset specifically for that: https://api.memegen.link/images/custom/_/enjoy_enjoy_enjoy_enjoy_enjoy_enjoy_enjoy_2.jpg?font=impact&background=https://latinsud.com/pub/meme/files/fernando-simon-covid.jpg

Let me know if you run into any more cases where the text is cut off.
