### ISSUE TITLE
Question: Have the captions for the astronaut meme changed recently?

### ISSUE THREAD

**Issue by Bradye1** [jacebrowning/memegen#861]
Hello! Please let me know if this is incorrect, but I believe you used to be able to provide 4 lines for the astronaut meme in order to have 2 lines for the dialog and 2 lines "labeling" the astronauts. The lines representing the dialog would also be positioned closer to the where the astronauts are standing.

Now it seems that it only makes use of 2 lines and simply displays them as a top line and bottom line.

For example, using the lines from [templates/astronaut/config.yml](https://github.com/jacebrowning/memegen/blob/main/templates/astronaut/config.yml) as a reference, I thought you could generate the following:
https://api.memegen.link/images/astronaut/Wait,_it's_round~q/Always_has_been/Flat_Earther/Science.png

Was just wondering if this may have changed recently. Thanks for the help!

**Comment by jacebrowning** [comment]
Thanks for the report! That image link looks correct to me.

As mentioned on https://github.com/jacebrowning/memegen/issues/857, I think there may be race condition where customizing a template can modify the base config on the filesystem (until Heroku Dynos restart). If you can provide specific steps to reproduce the issue that would be appreciated. Otherwise, I don't think there's any immediate action to take here.
